management:
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:8182,http://localhost:8185,http://localhost:8181
        allowed-methods: PUT,POST,GET,OPTIONS,DELETE
        allow-credentials: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boomitech?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: supplierservice
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
server:
  port: 8081
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:12002/oauth/check_token
    client:
      client-id: web
      client-secret: pin
      access-token-uri: http://localhost:12002/oauth/token
cloud:
  aws:
    credentials:
      access-key: "AKIAVE6BDCS3EWENNBTT"
      secret-key: "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"
    region:
      static: "us-east-1"
